---
apiVersion: batch/v1
kind: Job
metadata:
  name: backup-metabase
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        job: backup-metabase
    spec:
      serviceAccountName: backup-metabase
      restartPolicy: Never
      containers:
        - name: backup-metabase
          image: ghcr.io/mvandenburgh/metabase-backup:0.0.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-metabase
  namespace: monitoring

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backup-metabase
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backup-metabase
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: backup-metabase
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: backup-metabase
  apiGroup: rbac.authorization.k8s.io
