name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-image: opensearch-index-build-logs
            image-version: 0.0.6
          - docker-image: gitlab-error-processor
            image-version: 0.0.1
          - docker-image: upload-gitlab-failure-logs
            image-version: 0.0.2
          - docker-image: oom-tracker
            image-version: 0.0.1
          - docker-image: migrate-opensearch
            image-version: 0.0.1
          - docker-image: gh-gl-sync
            image-version: 0.0.23
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.docker-image }}
        id: docker-build-push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.docker-image }}
          file: ./${{ matrix.docker-image }}/Dockerfile
          push: true
          tags: ghcr.io/mvandenburgh/${{ matrix.docker-image }}:${{ matrix.image-version }}

  publish-win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-image: spack-win
            image-version: 0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push ${{ matrix.docker-image }}
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ matrix.docker-image }}
          directory: ./${{ matrix.docker-image }}
          dockerfile: ./${{ matrix.docker-image }}/Dockerfile
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platform: windows/amd64
          tags: ${{ matrix.image-version }}
